apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sonarbridge-dev
nameSuffix: -dev

resources:
  - ../../base

labels:
  - pairs:
      env: dev

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: sonarbridge-dev.cavom.lan
    target:
      kind: Ingress
  - patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/hostPath/path
        value: /data/kube-data/portail/logs/dev
      - op: replace
        path: /spec/template/spec/containers/0/envFrom
        value:
          - secretRef:
              name: sonarbridge-secret-dev
          - configMapRef:
              name: sonarbridge-config-dev
      - op: replace
        path: /spec/template/spec/containers/0/volumeMounts/0/mountPath
        value: /data/kube-data/portail/logs/dev/sonarbridge
    target:
      kind: Deployment

replacements:
  - source:
      kind: Middleware
      name: sonarbridge-ingress-redirect-https-dev
      fieldPath: metadata.name
    targets:
      - select:
          kind: IngressRoute
          name: sonarbridge-ingressroute-http
        fieldPaths:
          - spec.routes.0.middlewares.0.name

configMapGenerator:
  - name: sonarbridge-config
    behavior: merge
    envs:
      - configmap.env
    options:
      disableNameSuffixHash: true
      labels:
        deploy-order: "0"

secretGenerator:
  - name: sonarbridge-secret
    behavior: merge
    envs:
      - secret.env
    options:
      disableNameSuffixHash: true
      labels:
        deploy-order: "0"