apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarbridge-config
data:
  #  PORT: 80
  NODE_ENV: "${ENV}"
  LOG_LEVEL: "${ENV == 'prod' ? 'info' : 'debug'}"
  CORS_ORIGIN: "${ENV == 'prod' ? 'https://sonarbridge.cavom.lan' : '*'}"


  PORT: "9405"
  ENV: "dev"
  GITLAB_URL: "https://gitlab.cavom.lan/api/v4"

  # SonarQube Configuration
  SONARQUBE_URL: "https://sonarqube.cavom.lan/api"
  SONAR_EDITION: "ce"
