apiVersion: v1
kind: Secret
metadata:
  name: sonarbridge-secret
  namespace: NAMESPACE_NAME
data:
  SONARQUBE_TOKEN: squ_0740303005c32863b032cc84fc2c6b8651d59e88 #your-sonarqube-token
  WEBHOOK_SECRET: 112233445566778899z #your-webhook-secret-key
  GITLAB_TOKEN: glpat-xwRmChemzuWfKhyzLMuV #your-gitlab-access-token, or get the GITLAB_TOKEN in pipeline ENV if it is CI
  GITLAB_WEBHOOK_TOKEN: 7a5dd795327d00844d7e0c5c7dc682a2a1ec4521d1ea989fd1d20fd71aab9cfd #your-gitlab-webhook-token. You can get it by hinting `openssl rand -hex 32` and use the output